#!/usr/bin/python3
"""
--! This Script For Find_Admin_Page
--! My Info
--! Name is : Mahmoud Saber
--! WHatsApp is : 01117374028
"""
# import module

import os , sys
import urllib.request
import time

#############################

# info Coder

os.system("figlet Find_Admin")
time.sleep(1)
os.system("clear")
os.system("figlet Start-GET")
print("[*] Cdedd By : Mahmoud S.ALi")
print("[*] Facebook : https://www.facebook.com/mody.saber.96343405")
print("[*] WhatsApp : 01117374028")
time.sleep(2)

#####################
# def restary


def restart_program():
    python = sys.executable
    os.execl(python, python, * sys.argv)


curdir = os.getcwd()

def GET_ADMIN(url):
    try :
        ulropen = urllib.request.urlopen(url)
        login = ['admin/','admin1/','admin2/','admin3/','admin4/','admin5/','administrator/','usuarios/','usuario/','administrator/','moderrator/','webadmin/','adminarea/','bb-admin/','adminLogin/',
                'memberadmin/','administratorlogin/','adm/','admin/account.php','admin/index.php','admin/login.php','admin/admin.php','admin/account.php',
                'admin_area/admin.php','admin_area/login.php','siteadmin/login.php','siteadmin/index.php','siteadmin/login.html','admin/account.html','admin/index.html','admin/login.html','admin/admin.html',
                'admin_area/index.php','bb-admin/index.php','bb-admin/login.php','bb-admin/admin.php','bb-admin/home.php','admin/home.php','admin_area/login.html','admin_area/index.html',
                'admin/controlpanel.php','admin.php','admincp/indx.asp','admincp/login.asp','admincp/index.html','admin/account.html','adminpanel.html','webadmin.html',
                'webadmin/index.html','webadmin/admin.html','webadmin/login.html','admin/admin_login.html','index.php/admin','admin_login.html','panel-administracion/login.html',
                'admin/cp.php','cp.php','administrator/index.php','administrator/login.php','nsw/admin/login.php','webadmin/login.php','admin/admin_login.php','panel-administrator/login.php',
                'admin2/login.php','adm/index.php','adm.php','affiliate.php','adm_auth.php','memberadmin.php','administratorlogin.php',
                'cp.php','cp.html','modelsearch/login.php','panel-administracion/login.php','admin/',
                'administrator/',
                'admin1/',
                'admin2/',
                'admin3/',
                'admin4/',
                'admin5/',
                'usuarios/',
                'usuario/',
                'moderator/',
                'webadmin/',
                'adminarea/',
                'bb-admin/',
                'adminLogin/',
                'admin_area/',
                'panel-administracion/',
                'instadmin/',
                'memberadmin/',
                'administratorlogin/',
                'adm/',
                'admin/account.php',
                'admin/index.php',
                'admin/login.php',
                'admin/admin.php',
                'admin_area/admin.php',
                'admin_area/login.php',
                'siteadmin/login.php',
                'siteadmin/index.php',
                'siteadmin/login.html',
                'admin/account.html',
                'admin/index.html',
                'admin/login.html',
                'admin/admin.html',
                'admin_area/index.php',
                'bb-admin/index.php',
                'bb-admin/login.php',
                'bb-admin/admin.php',
                'admin/home.php',
                'admin_area/login.html',
                'admin_area/index.html',
                'admin/controlpanel.php',
                'admin.php',
                'admincp/index.asp',
                'admincp/login.asp',
                'admincp/index.html',
                'adminpanel.html',
                'webadmin.html',
                'webadmin/index.html',
                'webadmin/admin.html',
                'webadmin/login.html',
                'admin/admin_login.html',
                'admin_login.html',
                'panel-administracion/login.html',
                'admin/cp.php',
                'cp.php',
                'administrator/index.php',
                'administrator/login.php',
                'nsw/admin/login.php',
                'webadmin/login.php',
                'admin/admin_login.php',
                'admin_login.php',
                'administrator/account.php',
                'administrator.php',
                'admin_area/admin.html',
                'pages/admin/admin-login.php',
                'admin/admin-login.php',
                'admin-login.php',
                'bb-admin/index.html',
                'bb-admin/login.html',
                'acceso.php',
                'bb-admin/admin.html',
                'admin/home.html',
                'login.php',
                'modelsearch/login.php',
                'moderator.php',
                'moderator/login.php',
                'moderator/admin.php',
                'account.php',
                'pages/admin/admin-login.html',
                'admin/admin-login.html',
                'admin-login.html',
                'controlpanel.php',
                'admincontrol.php',
                'admin/adminLogin.html',
                'adminLogin.html',
                'home.html',
                'rcjakar/admin/login.php',
                'adminarea/index.html',
                'adminarea/admin.html',
                'webadmin.php',
                'webadmin/index.php',
                'webadmin/admin.php',
                'admin/controlpanel.html',
                'admin.html',
                'admin/cp.html',
                'cp.html',
                'adminpanel.php',
                'moderator.html',
                'administrator/index.html',
                'administrator/login.html',
                'user.html',
                'administrator/account.html',
                'administrator.html',
                'login.html',
                'modelsearch/login.html',
                'moderator/login.html',
                'adminarea/login.html',
                'panel-administracion/index.html',
                'panel-administracion/admin.html',
                'modelsearch/index.html',
                'modelsearch/admin.html',
                'admincontrol/login.html',
                'adm/index.html',
                'adm.html',
                'moderator/admin.html',
                'user.php',
                'account.html',
                'controlpanel.html',
                'admincontrol.html',
                'panel-administracion/login.php',
                'wp-login.php',
                'adminLogin.php',
                'admin/adminLogin.php',
                'home.php',
                'adminarea/index.php',
                'adminarea/admin.php',
                'adminarea/login.php',
                'panel-administracion/index.php',
                'panel-administracion/admin.php',
                'modelsearch/index.php',
                'modelsearch/admin.php',
                'admincontrol/login.php',
                'adm/admloginuser.php',
                'admloginuser.php',
                'admin2.php',
                'admin2/login.php',
                'admin2/index.php',
                'usuarios/login.php',
                'adm/index.php',
                'adm.php',
                'affiliate.php',
                'adm_auth.php',
                'memberadmin.php',
                'administratorlogin.php',
                'account.asp',
                'admin/account.asp',
                'admin/index.asp',
                'admin/login.asp',
                'admin/admin.asp',
                'admin_area/admin.asp',
                'admin_area/login.asp',
                'admin_area/index.asp',
                'bb-admin/index.asp',
                'bb-admin/login.asp',
                'bb-admin/admin.asp',
                'admin/home.asp',
                'admin/controlpanel.asp',
                'admin.asp',
                'pages/admin/admin-login.asp',
                'admin/admin-login.asp',
                'admin-login.asp',
                'admin/cp.asp',
                'cp.asp',
                'administrator/account.asp',
                'administrator.asp',
                'acceso.asp',
                'login.asp',
                'modelsearch/login.asp',
                'moderator.asp',
                'moderator/login.asp',
                'administrator/login.asp',
                'moderator/admin.asp',
                'controlpanel.asp',
                'user.asp',
                'admincontrol.asp',
                'adminpanel.asp',
                'webadmin.asp',
                'webadmin/index.asp',
                'webadmin/admin.asp',
                'webadmin/login.asp',
                'admin/admin_login.asp',
                'admin_login.asp',
                'panel-administracion/login.asp',
                'adminLogin.asp',
                'admin/adminLogin.asp',
                'home.asp',
                'superuser/',
                'superuser.%EXT%',
                'access/',
                'access.%EXT%',
                'sysadm/',
                'sysadm.%EXT%',
                'superman/',
                'supervisor/',
                'panel.%EXT%',
                'control/',
                'control.%EXT%',
                'member/',
                'member.%EXT%',
                'members/',
                'user/',
                'user.%EXT%',
                'cp/',
                'uvpanel/',
                'manage/',
                'manage.%EXT%',
                'management/',
                'management.%EXT%',
                'signin/',
                'signin.%EXT%',
                'log-in/',
                'log-in.%EXT%',
                'log_in/',
                'log_in.%EXT%',
                'sign_in/',
                'sign_in.%EXT%',
                'sign-in/',
                'sign-in.%EXT%',
                'users/',
                'users.%EXT%',
                'accounts/',
                'accounts.%EXT%',
                'bb-admin/login.%EXT%',
                'bb-admin/admin.%EXT%',
                'bb-admin/admin.html',
                'administrator/account.%EXT%',
                'relogin.htm',
                'relogin.html',
                'check.%EXT%',
                'relogin.%EXT%',
                'blog/wp-login.%EXT%',
                'user/admin.%EXT%',
                'users/admin.%EXT%',
                'registration/',
                'processlogin.%EXT%',
                'checklogin.%EXT%',
                'checkuser.%EXT%',
                'checkadmin.%EXT%',
                'isadmin.%EXT%',
                'authenticate.%EXT%',
                'authentication.%EXT%',
                'auth.%EXT%',
                'authuser.%EXT%',
                'authadmin.%EXT%',
                'cp.%EXT%',
                'modelsearch/login.%EXT%',
                'moderator.%EXT%',
                'moderator/',
                'controlpanel/',
                'controlpanel.%EXT%',
                'admincontrol.%EXT%',
                'adminpanel.%EXT%',
                'fileadmin/',
                'fileadmin.%EXT%',
                'sysadmin.%EXT%',
                'admin1.%EXT%',
                'admin1.html',
                'admin1.htm',
                'admin2.%EXT%',
                'admin2.html',
                'yonetim.%EXT%',
                'yonetim.html',
                'yonetici.%EXT%',
                'yonetici.html',
                'phpmyadmin/',
                'myadmin/',
                'ur-admin.%EXT%',
                'ur-admin/',
                'Server.%EXT%',
                'Server/',
                'wp-admin/',
                'administr8.%EXT%',
                'administr8/',
                'webadmin/',
                'webadmin.%EXT%',
                'administratie/',
                'admins/',
                'admins.%EXT%',
                'administrivia/',
                'Database_Administration/',
                'useradmin/'
                'sysadmins/'
                'sysadmins/'
                'admin1/',
                'system-administration/',
                'administrators/',
                'pgadmin/',
                'directadmin/',
                'staradmin/',
                'ServerAdministrator/',
                'SysAdmin/',
                'administer/',
                'LiveUser_Admin/',
                'sys-admin/',
                'typo3/',
                'panel/',
                'cpanel/',
                'cpanel_file/',
                'platz_login/',
                'rcLogin/',
                'blogindex/',
                'formslogin/',
                'autologin/',
                'manuallogin/',
                'simpleLogin/',
                'loginflat/',
                'utility_login/',
                'showlogin/',
                'memlogin/',
                'login-redirect/',
                'sub-login/',
                'wp-login/',
                'login1/',
                'dir-login/',
                'login_db/',
                'xlogin/',
                'smblogin/',
                'customer_login/',
                'UserLogin/',
                'login-us/',
                'acct_login/',
                'bigadmin/',
                'project-admins/',
                'phppgadmin/',
                'pureadmin/',
                'sql-admin/',
                'radmind/',
                'openvpnadmin/',
                'wizmysqladmin/',
                'vadmind/',
                'ezsqliteadmin/',
                'hpwebjetadmin/',
                'newsadmin/',
                'adminpro/',
                'Lotus_Domino_Admin/',
                'bbadmin/',
                'vmailadmin/',
                'Indy_admin/',
                'ccp14admin/',
                'irc-macadmin/',
                'banneradmin/',
                'sshadmin/',
                'phpldapadmin/',
                'macadmin/',
                'administratoraccounts/',
                'admin4_account/',
                'admin4_colon/',
                'radmind-1/',
                'Super-Admin/',
                'AdminTools/',
                'cmsadmin/',
                'SysAdmin2/',
                'globes_admin/',
                'cadmins/',
                'phpSQLiteAdmin/',
                'navSiteAdmin/',
                'server_admin_small/',
                'logo_sysadmin/',
                'power_user/',
                'system_administration/',
                'ss_vms_admin_sm/',
                'bb-admin/',
                'panel-administracion/',
                'instadmin/',
                'memberadmin/',
                'administratorlogin/',
                'adm.%EXT%',
                'admin_login.%EXT%',
                'panel-administracion/login.%EXT%',
                'pages/admin/admin-login.%EXT%',
                'pages/admin/',
                'acceso.%EXT%',
                'admincp/login.%EXT%',
                'admincp/',
                'adminarea/',
                'admincontrol/',
                'affiliate.%EXT%',
                'adm_auth.%EXT%',
                'memberadmin.%EXT%',
                'administratorlogin.%EXT%',
                'modules/admin/',
                'administrators.%EXT%',
                'siteadmin/',
                'siteadmin.%EXT%',
                'adminsite/',
                'kpanel/',
                'vorod/',
                'vorod.%EXT%',
                'vorud/',
                'vorud.%EXT%',
                'adminpanel/',
                'PSUser/',
                'secure/',
                'webmaster/',
                'webmaster.%EXT%',
                'autologin.%EXT%',
                'userlogin.%EXT%',
                'admin_area.%EXT%',
                'cmsadmin.%EXT%',
                'security/',
                'usr/',
                'root/',
                'secret/',
                'admin/login.%EXT%',
                'admin/adminLogin.%EXT%',
                'moderator.php',
                'moderator.html',
                'moderator/login.%EXT%',
                'moderator/admin.%EXT%',
                'yonetici.%EXT%',
                '0admin/',
                '0manager/',
                'aadmin/',
                'cgi-bin/login%EXT%',
                'login1%EXT%',
                'login_admin/',
                'login_admin%EXT%',
                'login_out/',
                'login_out%EXT%',
                'login_user%EXT%',
                'loginerror/',
                'loginok/',
                'loginsave/',
                'loginsuper/',
                'loginsuper%EXT%',
                'login%EXT%',
                'logout/',
                'logout%EXT%',
                'secrets/',
                'super1/',
                'super1%EXT%',
                'super_index%EXT%',
                'super_login%EXT%',
                'supermanager%EXT%',
                'superman%EXT%',
                'superuser%EXT%',
                'supervise/',
                'supervise/Login%EXT%',
                'super%EXT%']
        for i in login:
            Ourl = url+"/"+i
            try :
                open_url = urllib.request.urlopen(Ourl)
                print ("[+] Page Found >>>> "+Ourl)
            except urllib.error.HTTPError as msg:
                print ("[-] Page Not Found >>>>> "+Ourl)
                print (msg)
    except urllib.error.URLError as msg2:
        print (url)
        print (msg2)
GET_ADMIN(input("Enter Your Site For GET_Page_Admin >> : "))





print("==================================================")
print(" The connections you requested had finished ")
if __name__ == "__main__":
    answer = input(" Do you want to info more? : Yes Or No > : ")
    if answer.strip() in "y Y yes Yes YES".split():
        restart_program()
    else:
        os.system("figlet Good Bye")
